// Demo data so the app is browsable before Firebase is wired up.
// Replace with live Firestore reads once src/lib/firebase.js has real config.

export const mockNurse = {
  id: 'nurse-demo-01',
  name: 'Chiamaka Eze',
  cadre: 'RN',
  specialty: 'Critical Care',
  yearsExperience: 6,
  licenseNumber: 'NMCN/RN/2018/04471',
  verification: 'verified', // verified | pending | rejected
  rating: 4.8,
  shiftsCompleted: 32,
};

export const mockShifts = [
  {
    id: 'SHF-0142',
    facility: 'Reddington Hospital',
    facilityId: 'facility-demo-seed',
    city: 'Victoria Island, Lagos',
    lat: 6.4281,
    lng: 3.4219,
    unit: 'ICU',
    cadre: 'RN',
    date: '2026-07-29',
    start: '19:00',
    end: '07:00',
    hours: 12,
    rate: 9500,
    status: 'open', // open | claimed | filled
    urgency: 'urgent', // urgent | normal
    facilityRating: 4.6,
  },
  {
    id: 'SHF-0143',
    facility: 'Lagoon Hospitals',
    city: 'Apapa, Lagos',
    lat: 6.4432,
    lng: 3.3592,
    unit: 'Labour Ward',
    cadre: 'RM',
    date: '2026-07-28',
    start: '07:00',
    end: '19:00',
    hours: 12,
    rate: 8000,
    status: 'open',
    urgency: 'normal',
    facilityRating: 4.4,
  },
  {
    id: 'SHF-0144',
    facility: 'National Hospital Abuja',
    city: 'Central Area, Abuja',
    lat: 9.0579,
    lng: 7.4951,
    unit: 'Accident & Emergency',
    cadre: 'RN',
    date: '2026-07-29',
    start: '07:00',
    end: '19:00',
    hours: 12,
    rate: 10000,
    status: 'open',
    urgency: 'urgent',
    facilityRating: 4.2,
  },
  {
    id: 'SHF-0145',
    facility: 'Havana Specialist Hospital',
    city: 'Wuse II, Abuja',
    lat: 9.0833,
    lng: 7.4833,
    unit: 'Paediatrics',
    cadre: 'RN',
    date: '2026-07-30',
    start: '19:00',
    end: '07:00',
    hours: 12,
    rate: 8500,
    status: 'open',
    urgency: 'normal',
    facilityRating: 4.7,
  },
  {
    id: 'SHF-0146',
    facility: 'Rivers State University Hospital',
    city: 'Port Harcourt',
    lat: 4.8156,
    lng: 7.0498,
    unit: 'Theatre',
    cadre: 'RN',
    date: '2026-07-28',
    start: '08:00',
    end: '16:00',
    hours: 8,
    rate: 7000,
    status: 'claimed',
    urgency: 'normal',
    facilityRating: 4.0,
  },
  {
    id: 'SHF-0147',
    facility: 'University College Hospital',
    city: 'Ibadan',
    lat: 7.3775,
    lng: 3.9470,
    unit: 'General Medicine',
    cadre: 'RN',
    date: '2026-07-31',
    start: '19:00',
    end: '07:00',
    hours: 12,
    rate: 7500,
    status: 'open',
    urgency: 'normal',
    facilityRating: 4.3,
  },
];

export const mockClaims = [
  {
    id: 'CLM-001',
    shiftId: 'SHF-0146',
    nurseId: 'nurse-demo-01',
    status: 'approved', // pending | approved | rejected | completed
    clockIn: null,
    clockOut: null,
  },
];
