// Seed data: hospital facilities across Lagos State and Ogun State, one open shift each.
// Generated for demo/local-dev use — merged into demoStore's in-memory data in DEMO_MODE.
// For a live Firestore project, run scripts/seedFirestore.js instead (see that file for usage).

export const seedFacilities = [
  {
    "id": "facility-seed-001",
    "name": "Agege General Hospital",
    "city": "Agege, Lagos",
    "lga": "Agege",
    "state": "Lagos",
    "lat": 6.6282,
    "lng": 3.3363
  },
  {
    "id": "facility-seed-002",
    "name": "Chygor-Cole Specialist Hospital, Abule-Egba",
    "city": "Agege, Lagos",
    "lga": "Agege",
    "state": "Lagos",
    "lat": 6.6022,
    "lng": 3.33
  },
  {
    "id": "facility-seed-003",
    "name": "Isolo Ejigbo Comprehensive Health Centre",
    "city": "Agege, Lagos",
    "lga": "Agege",
    "state": "Lagos",
    "lat": 6.6172,
    "lng": 3.3212
  },
  {
    "id": "facility-seed-004",
    "name": "Ajeromi General Hospital",
    "city": "Ajeromi-Ifelodun, Lagos",
    "lga": "Ajeromi-Ifelodun",
    "state": "Lagos",
    "lat": 6.4512,
    "lng": 3.3227
  },
  {
    "id": "facility-seed-005",
    "name": "Trinity Specialist Hospital, Ajegunle",
    "city": "Ajeromi-Ifelodun, Lagos",
    "lga": "Ajeromi-Ifelodun",
    "state": "Lagos",
    "lat": 6.4536,
    "lng": 3.316
  },
  {
    "id": "facility-seed-006",
    "name": "Ajegunle Comprehensive Health Centre",
    "city": "Ajeromi-Ifelodun, Lagos",
    "lga": "Ajeromi-Ifelodun",
    "state": "Lagos",
    "lat": 6.4588,
    "lng": 3.3217
  },
  {
    "id": "facility-seed-007",
    "name": "Alimosho General Hospital, Igando",
    "city": "Alimosho, Lagos",
    "lga": "Alimosho",
    "state": "Lagos",
    "lat": 6.5695,
    "lng": 3.2993
  },
  {
    "id": "facility-seed-008",
    "name": "Krown Hospital, Egbeda",
    "city": "Alimosho, Lagos",
    "lga": "Alimosho",
    "state": "Lagos",
    "lat": 6.5744,
    "lng": 3.2816
  },
  {
    "id": "facility-seed-009",
    "name": "Mercy Stripes Specialist Hospital, Shasha",
    "city": "Alimosho, Lagos",
    "lga": "Alimosho",
    "state": "Lagos",
    "lat": 6.5807,
    "lng": 3.275
  },
  {
    "id": "facility-seed-010",
    "name": "Amuwo-Odofin General Hospital, Festac",
    "city": "Amuwo-Odofin, Lagos",
    "lga": "Amuwo-Odofin",
    "state": "Lagos",
    "lat": 6.4808,
    "lng": 3.2928
  },
  {
    "id": "facility-seed-011",
    "name": "Trade Fair General Hospital",
    "city": "Amuwo-Odofin, Lagos",
    "lga": "Amuwo-Odofin",
    "state": "Lagos",
    "lat": 6.4763,
    "lng": 3.2979
  },
  {
    "id": "facility-seed-012",
    "name": "Festac Links Hospital",
    "city": "Amuwo-Odofin, Lagos",
    "lga": "Amuwo-Odofin",
    "state": "Lagos",
    "lat": 6.4571,
    "lng": 3.2709
  },
  {
    "id": "facility-seed-013",
    "name": "Apapa General Hospital",
    "city": "Apapa, Lagos",
    "lga": "Apapa",
    "state": "Lagos",
    "lat": 6.4581,
    "lng": 3.351
  },
  {
    "id": "facility-seed-014",
    "name": "Lagoon Hospitals, Apapa",
    "city": "Apapa, Lagos",
    "lga": "Apapa",
    "state": "Lagos",
    "lat": 6.4527,
    "lng": 3.3725
  },
  {
    "id": "facility-seed-015",
    "name": "Malu Road Health Centre, Apapa",
    "city": "Apapa, Lagos",
    "lga": "Apapa",
    "state": "Lagos",
    "lat": 6.4415,
    "lng": 3.3642
  },
  {
    "id": "facility-seed-016",
    "name": "Badagry General Hospital",
    "city": "Badagry, Lagos",
    "lga": "Badagry",
    "state": "Lagos",
    "lat": 6.4288,
    "lng": 2.8919
  },
  {
    "id": "facility-seed-017",
    "name": "Adebayo Living Tower Hospital, Badagry",
    "city": "Badagry, Lagos",
    "lga": "Badagry",
    "state": "Lagos",
    "lat": 6.414,
    "lng": 2.8834
  },
  {
    "id": "facility-seed-018",
    "name": "Badagry Cottage Hospital, Topo",
    "city": "Badagry, Lagos",
    "lga": "Badagry",
    "state": "Lagos",
    "lat": 6.4203,
    "lng": 2.8821
  },
  {
    "id": "facility-seed-019",
    "name": "Epe General Hospital",
    "city": "Epe, Lagos",
    "lga": "Epe",
    "state": "Lagos",
    "lat": 6.5779,
    "lng": 3.9905
  },
  {
    "id": "facility-seed-020",
    "name": "Epe Comprehensive Health Centre",
    "city": "Epe, Lagos",
    "lga": "Epe",
    "state": "Lagos",
    "lat": 6.591,
    "lng": 3.9706
  },
  {
    "id": "facility-seed-021",
    "name": "Epe Cottage Hospital",
    "city": "Epe, Lagos",
    "lga": "Epe",
    "state": "Lagos",
    "lat": 6.5849,
    "lng": 3.9777
  },
  {
    "id": "facility-seed-022",
    "name": "Reddington Hospital, Victoria Island",
    "city": "Eti-Osa, Lagos",
    "lga": "Eti-Osa",
    "state": "Lagos",
    "lat": 6.4329,
    "lng": 3.4274
  },
  {
    "id": "facility-seed-023",
    "name": "Vedic Lifecare Hospital, Lekki Phase 1",
    "city": "Eti-Osa, Lagos",
    "lga": "Eti-Osa",
    "state": "Lagos",
    "lat": 6.4257,
    "lng": 3.4335
  },
  {
    "id": "facility-seed-024",
    "name": "Ave Maria Hospital, Lekki",
    "city": "Eti-Osa, Lagos",
    "lga": "Eti-Osa",
    "state": "Lagos",
    "lat": 6.4172,
    "lng": 3.4197
  },
  {
    "id": "facility-seed-025",
    "name": "Ibeju-Lekki General Hospital",
    "city": "Ibeju-Lekki, Lagos",
    "lga": "Ibeju-Lekki",
    "state": "Lagos",
    "lat": 6.4649,
    "lng": 3.6796
  },
  {
    "id": "facility-seed-026",
    "name": "Etta Atlantic Memorial Hospital, Ikate",
    "city": "Ibeju-Lekki, Lagos",
    "lga": "Ibeju-Lekki",
    "state": "Lagos",
    "lat": 6.4699,
    "lng": 3.6771
  },
  {
    "id": "facility-seed-027",
    "name": "Ifako-Ijaiye General Hospital",
    "city": "Ifako-Ijaiye, Lagos",
    "lga": "Ifako-Ijaiye",
    "state": "Lagos",
    "lat": 6.6517,
    "lng": 3.2858
  },
  {
    "id": "facility-seed-028",
    "name": "Holy Trinity Hospital, Iju",
    "city": "Ifako-Ijaiye, Lagos",
    "lga": "Ifako-Ijaiye",
    "state": "Lagos",
    "lat": 6.6566,
    "lng": 3.3014
  },
  {
    "id": "facility-seed-029",
    "name": "Lagos State University Teaching Hospital (LASUTH)",
    "city": "Ikeja, Lagos",
    "lga": "Ikeja",
    "state": "Lagos",
    "lat": 6.5994,
    "lng": 3.3453
  },
  {
    "id": "facility-seed-030",
    "name": "Eko Hospital, Ikeja",
    "city": "Ikeja, Lagos",
    "lga": "Ikeja",
    "state": "Lagos",
    "lat": 6.6164,
    "lng": 3.359
  },
  {
    "id": "facility-seed-031",
    "name": "Duchess International Hospital, Ikeja",
    "city": "Ikeja, Lagos",
    "lga": "Ikeja",
    "state": "Lagos",
    "lat": 6.6085,
    "lng": 3.361
  },
  {
    "id": "facility-seed-032",
    "name": "Ikorodu General Hospital",
    "city": "Ikorodu, Lagos",
    "lga": "Ikorodu",
    "state": "Lagos",
    "lat": 6.613,
    "lng": 3.5028
  },
  {
    "id": "facility-seed-033",
    "name": "Ikorodu Comprehensive Health Centre",
    "city": "Ikorodu, Lagos",
    "lga": "Ikorodu",
    "state": "Lagos",
    "lat": 6.6169,
    "lng": 3.5177
  },
  {
    "id": "facility-seed-034",
    "name": "Gbagada General Hospital",
    "city": "Kosofe, Lagos",
    "lga": "Kosofe",
    "state": "Lagos",
    "lat": 6.5743,
    "lng": 3.3976
  },
  {
    "id": "facility-seed-035",
    "name": "Isheri General Hospital, Ketu",
    "city": "Kosofe, Lagos",
    "lga": "Kosofe",
    "state": "Lagos",
    "lat": 6.5856,
    "lng": 3.376
  },
  {
    "id": "facility-seed-036",
    "name": "Lagos Island General Hospital",
    "city": "Lagos Island, Lagos",
    "lga": "Lagos Island",
    "state": "Lagos",
    "lat": 6.4685,
    "lng": 3.3892
  },
  {
    "id": "facility-seed-037",
    "name": "Massey Street Childrens Hospital",
    "city": "Lagos Island, Lagos",
    "lga": "Lagos Island",
    "state": "Lagos",
    "lat": 6.4667,
    "lng": 3.3882
  },
  {
    "id": "facility-seed-038",
    "name": "St. Nicholas Hospital, Lagos Island",
    "city": "Lagos Island, Lagos",
    "lga": "Lagos Island",
    "state": "Lagos",
    "lat": 6.4532,
    "lng": 3.4017
  },
  {
    "id": "facility-seed-039",
    "name": "Federal Medical Centre, Ebute-Metta",
    "city": "Lagos Mainland, Lagos",
    "lga": "Lagos Mainland",
    "state": "Lagos",
    "lat": 6.4913,
    "lng": 3.3809
  },
  {
    "id": "facility-seed-040",
    "name": "Lagos University Teaching Hospital (LUTH)",
    "city": "Lagos Mainland, Lagos",
    "lga": "Lagos Mainland",
    "state": "Lagos",
    "lat": 6.4862,
    "lng": 3.3969
  },
  {
    "id": "facility-seed-041",
    "name": "Mushin General Hospital",
    "city": "Mushin, Lagos",
    "lga": "Mushin",
    "state": "Lagos",
    "lat": 6.5463,
    "lng": 3.3486
  },
  {
    "id": "facility-seed-042",
    "name": "Maryland Specialist Hospital, Mushin",
    "city": "Mushin, Lagos",
    "lga": "Mushin",
    "state": "Lagos",
    "lat": 6.5319,
    "lng": 3.3456
  },
  {
    "id": "facility-seed-043",
    "name": "Nigerian Navy Reference Hospital, Ojo",
    "city": "Ojo, Lagos",
    "lga": "Ojo",
    "state": "Lagos",
    "lat": 6.4541,
    "lng": 3.1785
  },
  {
    "id": "facility-seed-044",
    "name": "Ojo General Hospital",
    "city": "Ojo, Lagos",
    "lga": "Ojo",
    "state": "Lagos",
    "lat": 6.4684,
    "lng": 3.1976
  },
  {
    "id": "facility-seed-045",
    "name": "Isolo General Hospital",
    "city": "Oshodi-Isolo, Lagos",
    "lga": "Oshodi-Isolo",
    "state": "Lagos",
    "lat": 6.5356,
    "lng": 3.3121
  },
  {
    "id": "facility-seed-046",
    "name": "Wind of Grace Hospital, Okota",
    "city": "Oshodi-Isolo, Lagos",
    "lga": "Oshodi-Isolo",
    "state": "Lagos",
    "lat": 6.5202,
    "lng": 3.3298
  },
  {
    "id": "facility-seed-047",
    "name": "National Orthopaedic Hospital, Igbobi",
    "city": "Somolu, Lagos",
    "lga": "Somolu",
    "state": "Lagos",
    "lat": 6.539,
    "lng": 3.3859
  },
  {
    "id": "facility-seed-048",
    "name": "Somolu General Hospital",
    "city": "Somolu, Lagos",
    "lga": "Somolu",
    "state": "Lagos",
    "lat": 6.5279,
    "lng": 3.3875
  },
  {
    "id": "facility-seed-049",
    "name": "Randle General Hospital, Surulere",
    "city": "Surulere, Lagos",
    "lga": "Surulere",
    "state": "Lagos",
    "lat": 6.481,
    "lng": 3.3556
  },
  {
    "id": "facility-seed-050",
    "name": "Avon Medical Practice, Surulere",
    "city": "Surulere, Lagos",
    "lga": "Surulere",
    "state": "Lagos",
    "lat": 6.4867,
    "lng": 3.3637
  },
  {
    "id": "facility-seed-051",
    "name": "Federal Medical Centre, Abeokuta",
    "city": "Abeokuta North, Ogun",
    "lga": "Abeokuta North",
    "state": "Ogun",
    "lat": 7.1493,
    "lng": 3.3411
  },
  {
    "id": "facility-seed-052",
    "name": "Federal Neuro-Psychiatric Hospital, Aro",
    "city": "Abeokuta South, Ogun",
    "lga": "Abeokuta South",
    "state": "Ogun",
    "lat": 7.1569,
    "lng": 3.3615
  },
  {
    "id": "facility-seed-053",
    "name": "State Hospital, Ota",
    "city": "Ado-Odo/Ota, Ogun",
    "lga": "Ado-Odo/Ota",
    "state": "Ogun",
    "lat": 6.6816,
    "lng": 3.2394
  },
  {
    "id": "facility-seed-054",
    "name": "General Hospital, Ayetoro",
    "city": "Yewa North, Ogun",
    "lga": "Yewa North",
    "state": "Ogun",
    "lat": 7.1638,
    "lng": 2.8589
  },
  {
    "id": "facility-seed-055",
    "name": "General Hospital, Ilaro",
    "city": "Yewa South, Ogun",
    "lga": "Yewa South",
    "state": "Ogun",
    "lat": 6.8945,
    "lng": 2.983
  },
  {
    "id": "facility-seed-056",
    "name": "General Hospital, Itori",
    "city": "Ewekoro, Ogun",
    "lga": "Ewekoro",
    "state": "Ogun",
    "lat": 6.9325,
    "lng": 3.2187
  },
  {
    "id": "facility-seed-057",
    "name": "General Hospital, Ifo",
    "city": "Ifo, Ogun",
    "lga": "Ifo",
    "state": "Ogun",
    "lat": 6.8103,
    "lng": 3.1834
  },
  {
    "id": "facility-seed-058",
    "name": "General Hospital, Ogbere",
    "city": "Ijebu East, Ogun",
    "lga": "Ijebu East",
    "state": "Ogun",
    "lat": 6.811,
    "lng": 4.0385
  },
  {
    "id": "facility-seed-059",
    "name": "General Hospital, Ijebu-Igbo",
    "city": "Ijebu North, Ogun",
    "lga": "Ijebu North",
    "state": "Ogun",
    "lat": 6.9702,
    "lng": 3.9046
  },
  {
    "id": "facility-seed-060",
    "name": "General Hospital, Atan",
    "city": "Ijebu North East, Ogun",
    "lga": "Ijebu North East",
    "state": "Ogun",
    "lat": 6.9401,
    "lng": 4.0471
  },
  {
    "id": "facility-seed-061",
    "name": "State Hospital, Ijebu-Ode",
    "city": "Ijebu Ode, Ogun",
    "lga": "Ijebu Ode",
    "state": "Ogun",
    "lat": 6.8081,
    "lng": 3.9126
  },
  {
    "id": "facility-seed-062",
    "name": "Dideolu Specialist Hospital, Ikenne",
    "city": "Ikenne, Ogun",
    "lga": "Ikenne",
    "state": "Ogun",
    "lat": 6.876,
    "lng": 3.7207
  },
  {
    "id": "facility-seed-063",
    "name": "General Hospital, Imeko",
    "city": "Imeko Afon, Ogun",
    "lga": "Imeko Afon",
    "state": "Ogun",
    "lat": 7.4188,
    "lng": 2.82
  },
  {
    "id": "facility-seed-064",
    "name": "General Hospital, Ipokia",
    "city": "Ipokia, Ogun",
    "lga": "Ipokia",
    "state": "Ogun",
    "lat": 6.6543,
    "lng": 2.8749
  },
  {
    "id": "facility-seed-065",
    "name": "General Hospital, Owode-Egba",
    "city": "Obafemi Owode, Ogun",
    "lga": "Obafemi Owode",
    "state": "Ogun",
    "lat": 6.8007,
    "lng": 3.4553
  },
  {
    "id": "facility-seed-066",
    "name": "General Hospital, Odeda",
    "city": "Odeda, Ogun",
    "lga": "Odeda",
    "state": "Ogun",
    "lat": 7.1696,
    "lng": 3.4415
  },
  {
    "id": "facility-seed-067",
    "name": "General Hospital, Odogbolu",
    "city": "Odogbolu, Ogun",
    "lga": "Odogbolu",
    "state": "Ogun",
    "lat": 6.8755,
    "lng": 3.8124
  },
  {
    "id": "facility-seed-068",
    "name": "General Hospital, Abigi",
    "city": "Ogun Waterside, Ogun",
    "lga": "Ogun Waterside",
    "state": "Ogun",
    "lat": 6.4633,
    "lng": 4.2447
  },
  {
    "id": "facility-seed-069",
    "name": "General Hospital, Iperu",
    "city": "Remo North, Ogun",
    "lga": "Remo North",
    "state": "Ogun",
    "lat": 6.9115,
    "lng": 3.7152
  },
  {
    "id": "facility-seed-070",
    "name": "Olabisi Onabanjo University Teaching Hospital (OOUTH), Sagamu",
    "city": "Sagamu, Ogun",
    "lga": "Sagamu",
    "state": "Ogun",
    "lat": 6.844,
    "lng": 3.6366
  }
];

export const seedShifts = [
  {
    "id": "SHF-SEED-001",
    "facility": "Agege General Hospital",
    "facilityId": "facility-seed-001",
    "city": "Agege, Lagos",
    "lat": 6.6282,
    "lng": 3.3363,
    "unit": "Accident & Emergency",
    "cadre": "RM",
    "date": "2026-07-29",
    "start": "19:00",
    "end": "07:00",
    "hours": 12,
    "rate": 6637,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.5
  },
  {
    "id": "SHF-SEED-002",
    "facility": "Chygor-Cole Specialist Hospital, Abule-Egba",
    "facilityId": "facility-seed-002",
    "city": "Agege, Lagos",
    "lat": 6.6022,
    "lng": 3.33,
    "unit": "Labour Ward",
    "cadre": "RN",
    "date": "2026-07-30",
    "start": "08:00",
    "end": "16:00",
    "hours": 8,
    "rate": 6774,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4
  },
  {
    "id": "SHF-SEED-003",
    "facility": "Isolo Ejigbo Comprehensive Health Centre",
    "facilityId": "facility-seed-003",
    "city": "Agege, Lagos",
    "lat": 6.6172,
    "lng": 3.3212,
    "unit": "General Medicine",
    "cadre": "RN",
    "date": "2026-07-31",
    "start": "07:00",
    "end": "19:00",
    "hours": 12,
    "rate": 6911,
    "status": "open",
    "urgency": "urgent",
    "facilityRating": 4.7
  },
  {
    "id": "SHF-SEED-004",
    "facility": "Ajeromi General Hospital",
    "facilityId": "facility-seed-004",
    "city": "Ajeromi-Ifelodun, Lagos",
    "lat": 6.4512,
    "lng": 3.3227,
    "unit": "Paediatrics",
    "cadre": "RM",
    "date": "2026-08-01",
    "start": "19:00",
    "end": "07:00",
    "hours": 12,
    "rate": 7048,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.2
  },
  {
    "id": "SHF-SEED-005",
    "facility": "Trinity Specialist Hospital, Ajegunle",
    "facilityId": "facility-seed-005",
    "city": "Ajeromi-Ifelodun, Lagos",
    "lat": 6.4536,
    "lng": 3.316,
    "unit": "Theatre",
    "cadre": "RN",
    "date": "2026-08-02",
    "start": "08:00",
    "end": "16:00",
    "hours": 8,
    "rate": 7185,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.9
  },
  {
    "id": "SHF-SEED-006",
    "facility": "Ajegunle Comprehensive Health Centre",
    "facilityId": "facility-seed-006",
    "city": "Ajeromi-Ifelodun, Lagos",
    "lat": 6.4588,
    "lng": 3.3217,
    "unit": "Renal/Dialysis",
    "cadre": "RN",
    "date": "2026-08-03",
    "start": "07:00",
    "end": "19:00",
    "hours": 12,
    "rate": 7322,
    "status": "open",
    "urgency": "urgent",
    "facilityRating": 4.4
  },
  {
    "id": "SHF-SEED-007",
    "facility": "Alimosho General Hospital, Igando",
    "facilityId": "facility-seed-007",
    "city": "Alimosho, Lagos",
    "lat": 6.5695,
    "lng": 3.2993,
    "unit": "Psychiatry",
    "cadre": "RM",
    "date": "2026-08-04",
    "start": "19:00",
    "end": "07:00",
    "hours": 12,
    "rate": 7459,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 3.9
  },
  {
    "id": "SHF-SEED-008",
    "facility": "Krown Hospital, Egbeda",
    "facilityId": "facility-seed-008",
    "city": "Alimosho, Lagos",
    "lat": 6.5744,
    "lng": 3.2816,
    "unit": "NICU",
    "cadre": "RN",
    "date": "2026-07-28",
    "start": "08:00",
    "end": "16:00",
    "hours": 8,
    "rate": 7596,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.6
  },
  {
    "id": "SHF-SEED-009",
    "facility": "Mercy Stripes Specialist Hospital, Shasha",
    "facilityId": "facility-seed-009",
    "city": "Alimosho, Lagos",
    "lat": 6.5807,
    "lng": 3.275,
    "unit": "Oncology",
    "cadre": "RN",
    "date": "2026-07-29",
    "start": "07:00",
    "end": "19:00",
    "hours": 12,
    "rate": 7733,
    "status": "open",
    "urgency": "urgent",
    "facilityRating": 4.1
  },
  {
    "id": "SHF-SEED-010",
    "facility": "Amuwo-Odofin General Hospital, Festac",
    "facilityId": "facility-seed-010",
    "city": "Amuwo-Odofin, Lagos",
    "lat": 6.4808,
    "lng": 3.2928,
    "unit": "ICU",
    "cadre": "RM",
    "date": "2026-07-30",
    "start": "19:00",
    "end": "07:00",
    "hours": 12,
    "rate": 7870,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.8
  },
  {
    "id": "SHF-SEED-011",
    "facility": "Trade Fair General Hospital",
    "facilityId": "facility-seed-011",
    "city": "Amuwo-Odofin, Lagos",
    "lat": 6.4763,
    "lng": 3.2979,
    "unit": "Accident & Emergency",
    "cadre": "RN",
    "date": "2026-07-31",
    "start": "08:00",
    "end": "16:00",
    "hours": 8,
    "rate": 8007,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.3
  },
  {
    "id": "SHF-SEED-012",
    "facility": "Festac Links Hospital",
    "facilityId": "facility-seed-012",
    "city": "Amuwo-Odofin, Lagos",
    "lat": 6.4571,
    "lng": 3.2709,
    "unit": "Labour Ward",
    "cadre": "RN",
    "date": "2026-08-01",
    "start": "07:00",
    "end": "19:00",
    "hours": 12,
    "rate": 8144,
    "status": "open",
    "urgency": "urgent",
    "facilityRating": 3.8
  },
  {
    "id": "SHF-SEED-013",
    "facility": "Apapa General Hospital",
    "facilityId": "facility-seed-013",
    "city": "Apapa, Lagos",
    "lat": 6.4581,
    "lng": 3.351,
    "unit": "General Medicine",
    "cadre": "RM",
    "date": "2026-08-02",
    "start": "19:00",
    "end": "07:00",
    "hours": 12,
    "rate": 8281,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.5
  },
  {
    "id": "SHF-SEED-014",
    "facility": "Lagoon Hospitals, Apapa",
    "facilityId": "facility-seed-014",
    "city": "Apapa, Lagos",
    "lat": 6.4527,
    "lng": 3.3725,
    "unit": "Paediatrics",
    "cadre": "RN",
    "date": "2026-08-03",
    "start": "08:00",
    "end": "16:00",
    "hours": 8,
    "rate": 8418,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4
  },
  {
    "id": "SHF-SEED-015",
    "facility": "Malu Road Health Centre, Apapa",
    "facilityId": "facility-seed-015",
    "city": "Apapa, Lagos",
    "lat": 6.4415,
    "lng": 3.3642,
    "unit": "Theatre",
    "cadre": "RN",
    "date": "2026-08-04",
    "start": "07:00",
    "end": "19:00",
    "hours": 12,
    "rate": 8555,
    "status": "open",
    "urgency": "urgent",
    "facilityRating": 4.7
  },
  {
    "id": "SHF-SEED-016",
    "facility": "Badagry General Hospital",
    "facilityId": "facility-seed-016",
    "city": "Badagry, Lagos",
    "lat": 6.4288,
    "lng": 2.8919,
    "unit": "Renal/Dialysis",
    "cadre": "RM",
    "date": "2026-07-28",
    "start": "19:00",
    "end": "07:00",
    "hours": 12,
    "rate": 8692,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.2
  },
  {
    "id": "SHF-SEED-017",
    "facility": "Adebayo Living Tower Hospital, Badagry",
    "facilityId": "facility-seed-017",
    "city": "Badagry, Lagos",
    "lat": 6.414,
    "lng": 2.8834,
    "unit": "Psychiatry",
    "cadre": "RN",
    "date": "2026-07-29",
    "start": "08:00",
    "end": "16:00",
    "hours": 8,
    "rate": 8829,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.9
  },
  {
    "id": "SHF-SEED-018",
    "facility": "Badagry Cottage Hospital, Topo",
    "facilityId": "facility-seed-018",
    "city": "Badagry, Lagos",
    "lat": 6.4203,
    "lng": 2.8821,
    "unit": "NICU",
    "cadre": "RN",
    "date": "2026-07-30",
    "start": "07:00",
    "end": "19:00",
    "hours": 12,
    "rate": 8966,
    "status": "open",
    "urgency": "urgent",
    "facilityRating": 4.4
  },
  {
    "id": "SHF-SEED-019",
    "facility": "Epe General Hospital",
    "facilityId": "facility-seed-019",
    "city": "Epe, Lagos",
    "lat": 6.5779,
    "lng": 3.9905,
    "unit": "Oncology",
    "cadre": "RM",
    "date": "2026-07-31",
    "start": "19:00",
    "end": "07:00",
    "hours": 12,
    "rate": 9103,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 3.9
  },
  {
    "id": "SHF-SEED-020",
    "facility": "Epe Comprehensive Health Centre",
    "facilityId": "facility-seed-020",
    "city": "Epe, Lagos",
    "lat": 6.591,
    "lng": 3.9706,
    "unit": "ICU",
    "cadre": "RN",
    "date": "2026-08-01",
    "start": "08:00",
    "end": "16:00",
    "hours": 8,
    "rate": 9240,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.6
  },
  {
    "id": "SHF-SEED-021",
    "facility": "Epe Cottage Hospital",
    "facilityId": "facility-seed-021",
    "city": "Epe, Lagos",
    "lat": 6.5849,
    "lng": 3.9777,
    "unit": "Accident & Emergency",
    "cadre": "RN",
    "date": "2026-08-02",
    "start": "07:00",
    "end": "19:00",
    "hours": 12,
    "rate": 9377,
    "status": "open",
    "urgency": "urgent",
    "facilityRating": 4.1
  },
  {
    "id": "SHF-SEED-022",
    "facility": "Reddington Hospital, Victoria Island",
    "facilityId": "facility-seed-022",
    "city": "Eti-Osa, Lagos",
    "lat": 6.4329,
    "lng": 3.4274,
    "unit": "Labour Ward",
    "cadre": "RM",
    "date": "2026-08-03",
    "start": "19:00",
    "end": "07:00",
    "hours": 12,
    "rate": 9514,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.8
  },
  {
    "id": "SHF-SEED-023",
    "facility": "Vedic Lifecare Hospital, Lekki Phase 1",
    "facilityId": "facility-seed-023",
    "city": "Eti-Osa, Lagos",
    "lat": 6.4257,
    "lng": 3.4335,
    "unit": "General Medicine",
    "cadre": "RN",
    "date": "2026-08-04",
    "start": "08:00",
    "end": "16:00",
    "hours": 8,
    "rate": 9651,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.3
  },
  {
    "id": "SHF-SEED-024",
    "facility": "Ave Maria Hospital, Lekki",
    "facilityId": "facility-seed-024",
    "city": "Eti-Osa, Lagos",
    "lat": 6.4172,
    "lng": 3.4197,
    "unit": "Paediatrics",
    "cadre": "RN",
    "date": "2026-07-28",
    "start": "07:00",
    "end": "19:00",
    "hours": 12,
    "rate": 9788,
    "status": "open",
    "urgency": "urgent",
    "facilityRating": 3.8
  },
  {
    "id": "SHF-SEED-025",
    "facility": "Ibeju-Lekki General Hospital",
    "facilityId": "facility-seed-025",
    "city": "Ibeju-Lekki, Lagos",
    "lat": 6.4649,
    "lng": 3.6796,
    "unit": "Theatre",
    "cadre": "RM",
    "date": "2026-07-29",
    "start": "19:00",
    "end": "07:00",
    "hours": 12,
    "rate": 9925,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.5
  },
  {
    "id": "SHF-SEED-026",
    "facility": "Etta Atlantic Memorial Hospital, Ikate",
    "facilityId": "facility-seed-026",
    "city": "Ibeju-Lekki, Lagos",
    "lat": 6.4699,
    "lng": 3.6771,
    "unit": "Renal/Dialysis",
    "cadre": "RN",
    "date": "2026-07-30",
    "start": "08:00",
    "end": "16:00",
    "hours": 8,
    "rate": 10062,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4
  },
  {
    "id": "SHF-SEED-027",
    "facility": "Ifako-Ijaiye General Hospital",
    "facilityId": "facility-seed-027",
    "city": "Ifako-Ijaiye, Lagos",
    "lat": 6.6517,
    "lng": 3.2858,
    "unit": "Psychiatry",
    "cadre": "RN",
    "date": "2026-07-31",
    "start": "07:00",
    "end": "19:00",
    "hours": 12,
    "rate": 10199,
    "status": "open",
    "urgency": "urgent",
    "facilityRating": 4.7
  },
  {
    "id": "SHF-SEED-028",
    "facility": "Holy Trinity Hospital, Iju",
    "facilityId": "facility-seed-028",
    "city": "Ifako-Ijaiye, Lagos",
    "lat": 6.6566,
    "lng": 3.3014,
    "unit": "NICU",
    "cadre": "RM",
    "date": "2026-08-01",
    "start": "19:00",
    "end": "07:00",
    "hours": 12,
    "rate": 10336,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.2
  },
  {
    "id": "SHF-SEED-029",
    "facility": "Lagos State University Teaching Hospital (LASUTH)",
    "facilityId": "facility-seed-029",
    "city": "Ikeja, Lagos",
    "lat": 6.5994,
    "lng": 3.3453,
    "unit": "Oncology",
    "cadre": "RN",
    "date": "2026-08-02",
    "start": "08:00",
    "end": "16:00",
    "hours": 8,
    "rate": 10473,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.9
  },
  {
    "id": "SHF-SEED-030",
    "facility": "Eko Hospital, Ikeja",
    "facilityId": "facility-seed-030",
    "city": "Ikeja, Lagos",
    "lat": 6.6164,
    "lng": 3.359,
    "unit": "ICU",
    "cadre": "RN",
    "date": "2026-08-03",
    "start": "07:00",
    "end": "19:00",
    "hours": 12,
    "rate": 10610,
    "status": "open",
    "urgency": "urgent",
    "facilityRating": 4.4
  },
  {
    "id": "SHF-SEED-031",
    "facility": "Duchess International Hospital, Ikeja",
    "facilityId": "facility-seed-031",
    "city": "Ikeja, Lagos",
    "lat": 6.6085,
    "lng": 3.361,
    "unit": "Accident & Emergency",
    "cadre": "RM",
    "date": "2026-08-04",
    "start": "19:00",
    "end": "07:00",
    "hours": 12,
    "rate": 10747,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 3.9
  },
  {
    "id": "SHF-SEED-032",
    "facility": "Ikorodu General Hospital",
    "facilityId": "facility-seed-032",
    "city": "Ikorodu, Lagos",
    "lat": 6.613,
    "lng": 3.5028,
    "unit": "Labour Ward",
    "cadre": "RN",
    "date": "2026-07-28",
    "start": "08:00",
    "end": "16:00",
    "hours": 8,
    "rate": 10884,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.6
  },
  {
    "id": "SHF-SEED-033",
    "facility": "Ikorodu Comprehensive Health Centre",
    "facilityId": "facility-seed-033",
    "city": "Ikorodu, Lagos",
    "lat": 6.6169,
    "lng": 3.5177,
    "unit": "General Medicine",
    "cadre": "RN",
    "date": "2026-07-29",
    "start": "07:00",
    "end": "19:00",
    "hours": 12,
    "rate": 6521,
    "status": "open",
    "urgency": "urgent",
    "facilityRating": 4.1
  },
  {
    "id": "SHF-SEED-034",
    "facility": "Gbagada General Hospital",
    "facilityId": "facility-seed-034",
    "city": "Kosofe, Lagos",
    "lat": 6.5743,
    "lng": 3.3976,
    "unit": "Paediatrics",
    "cadre": "RM",
    "date": "2026-07-30",
    "start": "19:00",
    "end": "07:00",
    "hours": 12,
    "rate": 6658,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.8
  },
  {
    "id": "SHF-SEED-035",
    "facility": "Isheri General Hospital, Ketu",
    "facilityId": "facility-seed-035",
    "city": "Kosofe, Lagos",
    "lat": 6.5856,
    "lng": 3.376,
    "unit": "Theatre",
    "cadre": "RN",
    "date": "2026-07-31",
    "start": "08:00",
    "end": "16:00",
    "hours": 8,
    "rate": 6795,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.3
  },
  {
    "id": "SHF-SEED-036",
    "facility": "Lagos Island General Hospital",
    "facilityId": "facility-seed-036",
    "city": "Lagos Island, Lagos",
    "lat": 6.4685,
    "lng": 3.3892,
    "unit": "Renal/Dialysis",
    "cadre": "RN",
    "date": "2026-08-01",
    "start": "07:00",
    "end": "19:00",
    "hours": 12,
    "rate": 6932,
    "status": "open",
    "urgency": "urgent",
    "facilityRating": 3.8
  },
  {
    "id": "SHF-SEED-037",
    "facility": "Massey Street Childrens Hospital",
    "facilityId": "facility-seed-037",
    "city": "Lagos Island, Lagos",
    "lat": 6.4667,
    "lng": 3.3882,
    "unit": "Psychiatry",
    "cadre": "RM",
    "date": "2026-08-02",
    "start": "19:00",
    "end": "07:00",
    "hours": 12,
    "rate": 7069,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.5
  },
  {
    "id": "SHF-SEED-038",
    "facility": "St. Nicholas Hospital, Lagos Island",
    "facilityId": "facility-seed-038",
    "city": "Lagos Island, Lagos",
    "lat": 6.4532,
    "lng": 3.4017,
    "unit": "NICU",
    "cadre": "RN",
    "date": "2026-08-03",
    "start": "08:00",
    "end": "16:00",
    "hours": 8,
    "rate": 7206,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4
  },
  {
    "id": "SHF-SEED-039",
    "facility": "Federal Medical Centre, Ebute-Metta",
    "facilityId": "facility-seed-039",
    "city": "Lagos Mainland, Lagos",
    "lat": 6.4913,
    "lng": 3.3809,
    "unit": "Oncology",
    "cadre": "RN",
    "date": "2026-08-04",
    "start": "07:00",
    "end": "19:00",
    "hours": 12,
    "rate": 7343,
    "status": "open",
    "urgency": "urgent",
    "facilityRating": 4.7
  },
  {
    "id": "SHF-SEED-040",
    "facility": "Lagos University Teaching Hospital (LUTH)",
    "facilityId": "facility-seed-040",
    "city": "Lagos Mainland, Lagos",
    "lat": 6.4862,
    "lng": 3.3969,
    "unit": "ICU",
    "cadre": "RM",
    "date": "2026-07-28",
    "start": "19:00",
    "end": "07:00",
    "hours": 12,
    "rate": 7480,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.2
  },
  {
    "id": "SHF-SEED-041",
    "facility": "Mushin General Hospital",
    "facilityId": "facility-seed-041",
    "city": "Mushin, Lagos",
    "lat": 6.5463,
    "lng": 3.3486,
    "unit": "Accident & Emergency",
    "cadre": "RN",
    "date": "2026-07-29",
    "start": "08:00",
    "end": "16:00",
    "hours": 8,
    "rate": 7617,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.9
  },
  {
    "id": "SHF-SEED-042",
    "facility": "Maryland Specialist Hospital, Mushin",
    "facilityId": "facility-seed-042",
    "city": "Mushin, Lagos",
    "lat": 6.5319,
    "lng": 3.3456,
    "unit": "Labour Ward",
    "cadre": "RN",
    "date": "2026-07-30",
    "start": "07:00",
    "end": "19:00",
    "hours": 12,
    "rate": 7754,
    "status": "open",
    "urgency": "urgent",
    "facilityRating": 4.4
  },
  {
    "id": "SHF-SEED-043",
    "facility": "Nigerian Navy Reference Hospital, Ojo",
    "facilityId": "facility-seed-043",
    "city": "Ojo, Lagos",
    "lat": 6.4541,
    "lng": 3.1785,
    "unit": "General Medicine",
    "cadre": "RM",
    "date": "2026-07-31",
    "start": "19:00",
    "end": "07:00",
    "hours": 12,
    "rate": 7891,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 3.9
  },
  {
    "id": "SHF-SEED-044",
    "facility": "Ojo General Hospital",
    "facilityId": "facility-seed-044",
    "city": "Ojo, Lagos",
    "lat": 6.4684,
    "lng": 3.1976,
    "unit": "Paediatrics",
    "cadre": "RN",
    "date": "2026-08-01",
    "start": "08:00",
    "end": "16:00",
    "hours": 8,
    "rate": 8028,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.6
  },
  {
    "id": "SHF-SEED-045",
    "facility": "Isolo General Hospital",
    "facilityId": "facility-seed-045",
    "city": "Oshodi-Isolo, Lagos",
    "lat": 6.5356,
    "lng": 3.3121,
    "unit": "Theatre",
    "cadre": "RN",
    "date": "2026-08-02",
    "start": "07:00",
    "end": "19:00",
    "hours": 12,
    "rate": 8165,
    "status": "open",
    "urgency": "urgent",
    "facilityRating": 4.1
  },
  {
    "id": "SHF-SEED-046",
    "facility": "Wind of Grace Hospital, Okota",
    "facilityId": "facility-seed-046",
    "city": "Oshodi-Isolo, Lagos",
    "lat": 6.5202,
    "lng": 3.3298,
    "unit": "Renal/Dialysis",
    "cadre": "RM",
    "date": "2026-08-03",
    "start": "19:00",
    "end": "07:00",
    "hours": 12,
    "rate": 8302,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.8
  },
  {
    "id": "SHF-SEED-047",
    "facility": "National Orthopaedic Hospital, Igbobi",
    "facilityId": "facility-seed-047",
    "city": "Somolu, Lagos",
    "lat": 6.539,
    "lng": 3.3859,
    "unit": "Psychiatry",
    "cadre": "RN",
    "date": "2026-08-04",
    "start": "08:00",
    "end": "16:00",
    "hours": 8,
    "rate": 8439,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.3
  },
  {
    "id": "SHF-SEED-048",
    "facility": "Somolu General Hospital",
    "facilityId": "facility-seed-048",
    "city": "Somolu, Lagos",
    "lat": 6.5279,
    "lng": 3.3875,
    "unit": "NICU",
    "cadre": "RN",
    "date": "2026-07-28",
    "start": "07:00",
    "end": "19:00",
    "hours": 12,
    "rate": 8576,
    "status": "open",
    "urgency": "urgent",
    "facilityRating": 3.8
  },
  {
    "id": "SHF-SEED-049",
    "facility": "Randle General Hospital, Surulere",
    "facilityId": "facility-seed-049",
    "city": "Surulere, Lagos",
    "lat": 6.481,
    "lng": 3.3556,
    "unit": "Oncology",
    "cadre": "RM",
    "date": "2026-07-29",
    "start": "19:00",
    "end": "07:00",
    "hours": 12,
    "rate": 8713,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.5
  },
  {
    "id": "SHF-SEED-050",
    "facility": "Avon Medical Practice, Surulere",
    "facilityId": "facility-seed-050",
    "city": "Surulere, Lagos",
    "lat": 6.4867,
    "lng": 3.3637,
    "unit": "ICU",
    "cadre": "RN",
    "date": "2026-07-30",
    "start": "08:00",
    "end": "16:00",
    "hours": 8,
    "rate": 8850,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4
  },
  {
    "id": "SHF-SEED-051",
    "facility": "Federal Medical Centre, Abeokuta",
    "facilityId": "facility-seed-051",
    "city": "Abeokuta North, Ogun",
    "lat": 7.1493,
    "lng": 3.3411,
    "unit": "Accident & Emergency",
    "cadre": "RN",
    "date": "2026-07-31",
    "start": "07:00",
    "end": "19:00",
    "hours": 12,
    "rate": 8987,
    "status": "open",
    "urgency": "urgent",
    "facilityRating": 4.7
  },
  {
    "id": "SHF-SEED-052",
    "facility": "Federal Neuro-Psychiatric Hospital, Aro",
    "facilityId": "facility-seed-052",
    "city": "Abeokuta South, Ogun",
    "lat": 7.1569,
    "lng": 3.3615,
    "unit": "Labour Ward",
    "cadre": "RM",
    "date": "2026-08-01",
    "start": "19:00",
    "end": "07:00",
    "hours": 12,
    "rate": 9124,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.2
  },
  {
    "id": "SHF-SEED-053",
    "facility": "State Hospital, Ota",
    "facilityId": "facility-seed-053",
    "city": "Ado-Odo/Ota, Ogun",
    "lat": 6.6816,
    "lng": 3.2394,
    "unit": "General Medicine",
    "cadre": "RN",
    "date": "2026-08-02",
    "start": "08:00",
    "end": "16:00",
    "hours": 8,
    "rate": 9261,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.9
  },
  {
    "id": "SHF-SEED-054",
    "facility": "General Hospital, Ayetoro",
    "facilityId": "facility-seed-054",
    "city": "Yewa North, Ogun",
    "lat": 7.1638,
    "lng": 2.8589,
    "unit": "Paediatrics",
    "cadre": "RN",
    "date": "2026-08-03",
    "start": "07:00",
    "end": "19:00",
    "hours": 12,
    "rate": 9398,
    "status": "open",
    "urgency": "urgent",
    "facilityRating": 4.4
  },
  {
    "id": "SHF-SEED-055",
    "facility": "General Hospital, Ilaro",
    "facilityId": "facility-seed-055",
    "city": "Yewa South, Ogun",
    "lat": 6.8945,
    "lng": 2.983,
    "unit": "Theatre",
    "cadre": "RM",
    "date": "2026-08-04",
    "start": "19:00",
    "end": "07:00",
    "hours": 12,
    "rate": 9535,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 3.9
  },
  {
    "id": "SHF-SEED-056",
    "facility": "General Hospital, Itori",
    "facilityId": "facility-seed-056",
    "city": "Ewekoro, Ogun",
    "lat": 6.9325,
    "lng": 3.2187,
    "unit": "Renal/Dialysis",
    "cadre": "RN",
    "date": "2026-07-28",
    "start": "08:00",
    "end": "16:00",
    "hours": 8,
    "rate": 9672,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.6
  },
  {
    "id": "SHF-SEED-057",
    "facility": "General Hospital, Ifo",
    "facilityId": "facility-seed-057",
    "city": "Ifo, Ogun",
    "lat": 6.8103,
    "lng": 3.1834,
    "unit": "Psychiatry",
    "cadre": "RN",
    "date": "2026-07-29",
    "start": "07:00",
    "end": "19:00",
    "hours": 12,
    "rate": 9809,
    "status": "open",
    "urgency": "urgent",
    "facilityRating": 4.1
  },
  {
    "id": "SHF-SEED-058",
    "facility": "General Hospital, Ogbere",
    "facilityId": "facility-seed-058",
    "city": "Ijebu East, Ogun",
    "lat": 6.811,
    "lng": 4.0385,
    "unit": "NICU",
    "cadre": "RM",
    "date": "2026-07-30",
    "start": "19:00",
    "end": "07:00",
    "hours": 12,
    "rate": 9946,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.8
  },
  {
    "id": "SHF-SEED-059",
    "facility": "General Hospital, Ijebu-Igbo",
    "facilityId": "facility-seed-059",
    "city": "Ijebu North, Ogun",
    "lat": 6.9702,
    "lng": 3.9046,
    "unit": "Oncology",
    "cadre": "RN",
    "date": "2026-07-31",
    "start": "08:00",
    "end": "16:00",
    "hours": 8,
    "rate": 10083,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.3
  },
  {
    "id": "SHF-SEED-060",
    "facility": "General Hospital, Atan",
    "facilityId": "facility-seed-060",
    "city": "Ijebu North East, Ogun",
    "lat": 6.9401,
    "lng": 4.0471,
    "unit": "ICU",
    "cadre": "RN",
    "date": "2026-08-01",
    "start": "07:00",
    "end": "19:00",
    "hours": 12,
    "rate": 10220,
    "status": "open",
    "urgency": "urgent",
    "facilityRating": 3.8
  },
  {
    "id": "SHF-SEED-061",
    "facility": "State Hospital, Ijebu-Ode",
    "facilityId": "facility-seed-061",
    "city": "Ijebu Ode, Ogun",
    "lat": 6.8081,
    "lng": 3.9126,
    "unit": "Accident & Emergency",
    "cadre": "RM",
    "date": "2026-08-02",
    "start": "19:00",
    "end": "07:00",
    "hours": 12,
    "rate": 10357,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.5
  },
  {
    "id": "SHF-SEED-062",
    "facility": "Dideolu Specialist Hospital, Ikenne",
    "facilityId": "facility-seed-062",
    "city": "Ikenne, Ogun",
    "lat": 6.876,
    "lng": 3.7207,
    "unit": "Labour Ward",
    "cadre": "RN",
    "date": "2026-08-03",
    "start": "08:00",
    "end": "16:00",
    "hours": 8,
    "rate": 10494,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4
  },
  {
    "id": "SHF-SEED-063",
    "facility": "General Hospital, Imeko",
    "facilityId": "facility-seed-063",
    "city": "Imeko Afon, Ogun",
    "lat": 7.4188,
    "lng": 2.82,
    "unit": "General Medicine",
    "cadre": "RN",
    "date": "2026-08-04",
    "start": "07:00",
    "end": "19:00",
    "hours": 12,
    "rate": 10631,
    "status": "open",
    "urgency": "urgent",
    "facilityRating": 4.7
  },
  {
    "id": "SHF-SEED-064",
    "facility": "General Hospital, Ipokia",
    "facilityId": "facility-seed-064",
    "city": "Ipokia, Ogun",
    "lat": 6.6543,
    "lng": 2.8749,
    "unit": "Paediatrics",
    "cadre": "RM",
    "date": "2026-07-28",
    "start": "19:00",
    "end": "07:00",
    "hours": 12,
    "rate": 10768,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.2
  },
  {
    "id": "SHF-SEED-065",
    "facility": "General Hospital, Owode-Egba",
    "facilityId": "facility-seed-065",
    "city": "Obafemi Owode, Ogun",
    "lat": 6.8007,
    "lng": 3.4553,
    "unit": "Theatre",
    "cadre": "RN",
    "date": "2026-07-29",
    "start": "08:00",
    "end": "16:00",
    "hours": 8,
    "rate": 10905,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.9
  },
  {
    "id": "SHF-SEED-066",
    "facility": "General Hospital, Odeda",
    "facilityId": "facility-seed-066",
    "city": "Odeda, Ogun",
    "lat": 7.1696,
    "lng": 3.4415,
    "unit": "Renal/Dialysis",
    "cadre": "RN",
    "date": "2026-07-30",
    "start": "07:00",
    "end": "19:00",
    "hours": 12,
    "rate": 6542,
    "status": "open",
    "urgency": "urgent",
    "facilityRating": 4.4
  },
  {
    "id": "SHF-SEED-067",
    "facility": "General Hospital, Odogbolu",
    "facilityId": "facility-seed-067",
    "city": "Odogbolu, Ogun",
    "lat": 6.8755,
    "lng": 3.8124,
    "unit": "Psychiatry",
    "cadre": "RM",
    "date": "2026-07-31",
    "start": "19:00",
    "end": "07:00",
    "hours": 12,
    "rate": 6679,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 3.9
  },
  {
    "id": "SHF-SEED-068",
    "facility": "General Hospital, Abigi",
    "facilityId": "facility-seed-068",
    "city": "Ogun Waterside, Ogun",
    "lat": 6.4633,
    "lng": 4.2447,
    "unit": "NICU",
    "cadre": "RN",
    "date": "2026-08-01",
    "start": "08:00",
    "end": "16:00",
    "hours": 8,
    "rate": 6816,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.6
  },
  {
    "id": "SHF-SEED-069",
    "facility": "General Hospital, Iperu",
    "facilityId": "facility-seed-069",
    "city": "Remo North, Ogun",
    "lat": 6.9115,
    "lng": 3.7152,
    "unit": "Oncology",
    "cadre": "RN",
    "date": "2026-08-02",
    "start": "07:00",
    "end": "19:00",
    "hours": 12,
    "rate": 6953,
    "status": "open",
    "urgency": "urgent",
    "facilityRating": 4.1
  },
  {
    "id": "SHF-SEED-070",
    "facility": "Olabisi Onabanjo University Teaching Hospital (OOUTH), Sagamu",
    "facilityId": "facility-seed-070",
    "city": "Sagamu, Ogun",
    "lat": 6.844,
    "lng": 3.6366,
    "unit": "ICU",
    "cadre": "RM",
    "date": "2026-08-03",
    "start": "19:00",
    "end": "07:00",
    "hours": 12,
    "rate": 7090,
    "status": "open",
    "urgency": "normal",
    "facilityRating": 4.8
  }
];
